---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
    driver:
      customize:
        cpus: 2
        memory: 6144
      network:
        - ["forwarded_port", {guest: 443, host: 9443, auto_correct: true}]
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["private_network", {type: 'dhcp', virtualbox__intnet: true, auto_config: false}]

suites:
  - name: default
    run_list:
      - recipe[ironic::default]
      - recipe[openstack-object-storage::setup] # Bug?  Should search run_list including include_recipe?
    attributes:
      openstack:
        endpoints:
          bind-host: 0.0.0.0
        bare-metal:
          enabled_drivers: 'fake,pxe_ssh,pxe_ipmitool,pxe_vbox,agent_vbox,agent_ssh,agent_ipmitool'
          swift:
            temp_url_duration: 3600
            container: glance
            endpoint_url: http://10.0.2.15:8080
            api_version: v1
            temp_url_key: password
