---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-7.1
    driver:
      customize:
        cpus: 4
        memory: 10240
        nicpromisc2: allow-all
      network:
        - ["forwarded_port", {guest: 443, host: 9443, auto_correct: true}]
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[fake::network_prep]
      - recipe[ironic::default]
      - recipe[openstack-object-storage::setup] # Bug?  Should search run_list including include_recipe?
      - recipe[fake::default]
    attributes:
      ironic:
        inspector:
          dnsmasq_interface: brbm
          dhcp_range: 192.168.50.201,192.168.50.250
          discovery_kernel: https://www.googledrive.com/host/0B7ZaljvkcyssMGN0bmk1OV9Fdnc
          discovery_initramfs: https://www.googledrive.com/host/0B7ZaljvkcyssWlUxdHJWYWI3M2M
          gateway: 192.168.50.1
        gateway: 10.0.2.2
        neutron:
          networks:
            baremetal:
              phys_net: physbare
          subnets:
            baremetal-subnet:
              network_name: baremetal
              network: 192.168.50.0
              mask: 24
              gateway: 192.168.50.1
              allocation_start: 192.168.50.100
              allocation_end: 192.168.50.200
      openstack:
        network:
          ml2:
            flat_networks: physbare
            network_vlan_ranges: physbare
          openvswitch:
            bridge_mappings: physbare:brbm
        endpoints:
          host: 10.0.2.15
          bind-host: 10.0.2.15
        compute:
          debug: True
        image:
          debug: True
          api:
            swift_store_auth_address: http://10.0.2.15:5000/v2.0
        bare-metal:
          debug: True
          api_url: http://10.0.2.15:6385
          tftp:
            server: 10.0.2.15
          enabled_drivers: fake,pxe_ssh,pxe_ipmitool,agent_ssh,agent_ipmitool
          swift:
            endpoint_url: http://10.0.2.15:8080
      rabbitmq:
        use_distro_version: true
