---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
    driver:
      customize:
        cpus: 2
        memory: 6144
      network:
        - ["forwarded_port", {guest: 443, host: 9443, auto_correct: true}]
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["private_network", {type: 'dhcp', virtualbox__intnet: true, auto_config: false}]

suites:
  - name: default
    run_list:
      - recipe[fake::vbox_driver_prereq]
      - recipe[ironic::default]
      - recipe[openstack-object-storage::setup] # Bug?  Should search run_list including include_recipe?
      - recipe[fake::default]
    attributes:
      ironic:
        interfaces:
          enp0s8:
            name: br-bare
            map_name: physbare
            net_name: baremetal
            ip: 192.168.50.1
            network: 192.168.50.0
            mask: 24
            allocation_start: 192.168.50.100
            allocation_end: 192.168.50.200
      openstack:
        endpoints:
          host: 10.0.2.15
          bind-host: 10.0.2.15
        compute:
          debug: True
        image:
          debug: True
          api:
            swift_store_auth_address: http://10.0.2.15:5000/v2.0
        bare-metal:
          debug: True
          api_url: http://10.0.2.15:6385
          tftp:
            server: 10.0.2.15
          enabled_drivers: fake,pxe_ssh,pxe_ipmitool,pxe_vbox,agent_vbox,agent_ssh,agent_ipmitool
          swift:
            endpoint_url: http://10.0.2.15:8080
            temp_url_key: 9NDaxGTfwRpHrL7j
