---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0 # Chef 12.4.0 is breaking mysql cookbook

platforms:
  - name: centos-7.0
    driver:
      customize:
        cpus: 2
        memory: 6144
      network:
        - ["forwarded_port", {guest: 443, host: 9443, auto_correct: true}]
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["private_network", {type: dhcp, auto_config: false, virtualbox__intnet: true}]

suites:
  - name: default
    run_list:
      - recipe[fake::vbox_driver_prereq]
      - recipe[ironic::default]
      - recipe[openstack-object-storage::setup] # Bug?  Should search run_list including include_recipe?
      - recipe[fake::default]
    attributes:
      ironic:
        inspector:
          dnsmasq_interface: br-bare
          dhcp_range: 192.168.50.201,192.168.50.250
          discovery_kernel: https://www.googledrive.com/host/0B7ZaljvkcyssMGN0bmk1OV9Fdnc
          discovery_initramfs: https://www.googledrive.com/host/0B7ZaljvkcyssWlUxdHJWYWI3M2M
        gateway: 10.0.2.2
        bridges:
          br-bare:
            interface: enp0s8
            phys_net: physbare
            ip: 192.168.50.1
            mask: 24
          br-gate:
            interface: enp0s3
            phys_net: physgate
            ip: 10.0.2.15
            mask: 24
        networks:
          baremetal:
            phys_net: physbare
            network: 192.168.50.0
            mask: 24
            gateway: 192.168.50.1
            allocation_start: 192.168.50.100
            allocation_end: 192.168.50.200
      openstack:
        endpoints:
          host: 10.0.2.15
          bind-host: 10.0.2.15
        compute:
          debug: True
        image:
          debug: True
          api:
            swift_store_auth_address: http://10.0.2.15:5000/v2.0
        bare-metal:
          debug: True
          api_url: http://10.0.2.15:6385
          tftp:
            server: 10.0.2.15
          enabled_drivers: fake,pxe_ssh,pxe_ipmitool,pxe_vbox,agent_vbox,agent_ssh,agent_ipmitool
          swift:
            endpoint_url: http://10.0.2.15:8080
      rabbitmq:
        use_distro_version: true

  - name: default-chef11
    provisioner:
      require_chef_omnibus: 11.16.4
    run_list:
      - recipe[fake::vbox_driver_prereq]
      - recipe[ironic::default]
      - recipe[openstack-object-storage::setup] # Bug?  Should search run_list including include_recipe?
      - recipe[fake::default]
    attributes:
      ironic:
        inspector:
          dnsmasq_interface: br-bare
          dhcp_range: 192.168.50.201,192.168.50.250
          discovery_kernel: https://www.googledrive.com/host/0B7ZaljvkcyssMGN0bmk1OV9Fdnc
          discovery_initramfs: https://www.googledrive.com/host/0B7ZaljvkcyssWlUxdHJWYWI3M2M
        gateway: 10.0.2.2
        bridges:
          br-bare:
            interface: enp0s8
            phys_net: physbare
            ip: 192.168.50.1
            mask: 24
          br-gate:
            interface: enp0s3
            phys_net: physgate
            ip: 10.0.2.15
            mask: 24
        networks:
          baremetal:
            phys_net: physbare
            network: 192.168.50.0
            mask: 24
            gateway: 192.168.50.1
            allocation_start: 192.168.50.100
            allocation_end: 192.168.50.200
      openstack:
        endpoints:
          host: 10.0.2.15
          bind-host: 10.0.2.15
        compute:
          debug: True
        image:
          debug: True
          api:
            swift_store_auth_address: http://10.0.2.15:5000/v2.0
        bare-metal:
          debug: True
          api_url: http://10.0.2.15:6385
          tftp:
            server: 10.0.2.15
          enabled_drivers: fake,pxe_ssh,pxe_ipmitool,pxe_vbox,agent_vbox,agent_ssh,agent_ipmitool
          swift:
            endpoint_url: http://10.0.2.15:8080
      rabbitmq:
        use_distro_version: true
